version: '3'

services:
  php:
    image: veniva/php-num-algs
    container_name: num-algs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    working_dir: /var/www
    stdin_open: true
    tty: true
